### ISSUE TITLE
Lesson 213 - Bun vs Go Grafana Dashboard

### ISSUE THREAD

**Issue by biclighter81** [antonputra/tutorials#305]
Hi,
your benchmarks are really interesting and important for Language and Framework selection. It would be really kind from you if you share your Grafana dashboard (JSON or Dashboard ID) from the latest Bun and Go comparison.

Keep up the good work.

Cheers, Moritz

**Comment by melroy89** [comment]
Just in general sharing the dashboards would be very nice. Including data gathering. This would make it more reproducible for others if needed.

Moreover, people could make improvements in both the data gathering scripts as well as the Grafana dashboard(s).

**Comment by blxs** [comment]
It would be awesome when you @antonputra share the dashboards with us ❤

**Comment by antonputra** [comment]
I don't like to share dashboards for each video because I have a lot of hardcoded values in queries and labels just to make them look nice. Most of the dashboards are based on this generic lesson on container monitoring, which actually uses variables and dynamic queries.

[How to monitor Containers in Kubernetes using Prometheus & cAdvisor?](https://github.com/antonputra/tutorials/blob/main/lessons/135)
